GET http://localhost:3000/users

###

GET http://localhost:3000/users/61dfae7efd2e57960d0

###

POST http://localhost:3000/users
Content-Type: application/json

{
  "name": "Yuka",
  "age": 4
}

###

DELETE http://localhost:3000/users/61de8f04aec214ef66299ba2